Update Build-KW.yml

diff --git a/.github/workflows/Build-KW.yml b/.github/workflows/Build-KW.yml
--- a/.github/workflows/Build-KW.yml
+++ b/.github/workflows/Build-KW.yml
@@ -24,6 +24,11 @@ jobs:
 
       - name: Sync Android-x86 source
         run: |
+          echo "Confirming Git Info . . ."
+          git config --global user.email "spoinkosgithub@gmail.com"
+          echo "Email: [SET]" || echo "Error Setting email"
+          git config --global user.name "WolfTech-Innovations"
+          echo "User: [SET]" || echo "Error Setting User"
           wsl repo init -u git://gitscm.sf.net/gitroot/android-x86/manifest -b pie-x86
           wsl repo sync --force-sync --no-tags --no-clone-bundle -j1
 
